# Generated by Django 5.2.4 on 2025-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_color_size_remove_product_discounted_price_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='app.product'),
        ),
    ]
