# Generated by Django 5.2.3 on 2025-06-28 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The প্রফেসর', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Main site logo shown in the header.', null=True, upload_to='site/')),
                ('about_title', models.CharField(blank=True, default='Who is The প্রফেসর?', max_length=255)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_story', models.TextField(blank=True, help_text='The main story or description for the About Us page.')),
                ('about_mission', models.TextField(blank=True, help_text='The mission statement for the About Us page.')),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional: If this price is set, it will be used as the product's current price.", max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category')),
            ],
        ),
    ]
